import os

DEBUG = True
SQLALCHEMY_DATABASE_URI = os.environ["DATABASE_URL"]
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
APP_SECRET_KEY = os.environ["APP_SECRET_KEY"]
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ["access", "refresh"]
JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
JWT_CSRF_IN_COOKIES = os.environ["JWT_CSRF_IN_COOKIES"]
JWT_TOKEN_LOCATION = os.environ["JWT_TOKEN_LOCATION"]
JWT_ACCESS_CSRF_HEADER_NAME = os.environ["JWT_ACCESS_CSRF_HEADER_NAME"]
JWT_REFRESH_CSRF_HEADER_NAME = os.environ["JWT_REFRESH_CSRF_HEADER_NAME"]
JWT_ACCESS_CSRF_COOKIE_NAME = os.environ["JWT_ACCESS_CSRF_COOKIE_NAME"]
JWT_REFRESH_CSRF_COOKIE_NAME = os.environ["JWT_REFRESH_CSRF_COOKIE_NAME"]