import os

DEBUG = True
SQLALCHEMY_DATABASE_URI = os.environ["TESTING_DATABASE_URL"]
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
APP_SECRET_KEY = os.environ["TESTING_APP_SECRET_KEY"]